#!/bin/bash
 
# Parametro referente ao ano
PARANO="${1}"
ARQUIVOSAIDA="${2}"

TAMANHOANO="${#PARANO}"

if [ ${TAMANHOANO} -ne 4  -o "${PARANO}" = "*" ]
then
	# Ano nao informado ou incorreto
	PARANO='*'
	FILTROPERIODO='*'
	CAMPOANO='TODOS'
else
	# Ano informado
	FILTROPERIODO="${PARANO}*"
	CAMPOANO="${PARANO}"
fi

	
	
	
DIRATUAL="`pwd`"
FATORDISTRIBUICAO=1
FONTEDADOS='L0 - ACESSO DIRETO'

LISTASATELITES=( 12 14 15 16 17 18 19)

for INDICEATUAL in `seq 0 6`
do

	# Dados referente ao satéte
	SATELITE="NOAA${LISTASATELITES[${INDICEATUAL}]}"
	NOMESATELITE="NOAA-${LISTASATELITES[${INDICEATUAL}]}"

	FILTROSATELITE="NOAA_*"
	FILTROEXTENSAO=""
	ORIGEM="/L0_NOAA${LISTASATELITES[${INDICEATUAL}]}"

	cd ${ORIGEM}

	TOTALCENAS="`find ${ORIGEM}/${FILTROPERIODO}  -name ${FILTROSATELITE}  -print | wc -l`"
	TOTALGERAL=$(( ${TOTALCENAS} * ${FATORDISTRIBUICAO} ))
	echo "${NOMESATELITE} : ${TOTALCENAS}  -  ${FATORDISTRIBUICAO}  -  ${TOTALGERAL}"
	
	echo "${CAMPOANO};${FONTEDADOS};${NOMESATELITE};${TOTALCENAS}"  >>  ${ARQUIVOSAIDA}
	
done
	

cd ${DIRATUAL}

