#!/bin/bash
 
# Parametro referente ao ano
PARANO="${1}"
ARQUIVOSAIDA="${2}"

TAMANHOANO="${#PARANO}"

if [ ${TAMANHOANO} -ne 4  -o "${PARANO}" = "*" ]
then
	# Ano nao informado ou incorreto
	PARANO='*'
	FILTROPERIODO='*'
	CAMPOANO='TODOS'
else
	# Ano informado
	FILTROPERIODO="${PARANO}*"
	CAMPOANO="${PARANO}"
fi
	
	
	
DIRATUAL="`pwd`"
FATORDISTRIBUICAO=1
FONTEDADOS='L0 - ACESSO DIRETO'

LISTASATELITES=( 12 13)

for INDICEATUAL in `seq 0 1`
do

	# Dados referente ao satéte
	SATELITE="GOES${LISTASATELITES[${INDICEATUAL}]}"
	NOMESATELITE="GOES-${LISTASATELITES[${INDICEATUAL}]}"

	FILTROEXTENSAO=""
	ORIGEM="/Level-0/GOES${LISTASATELITES[${INDICEATUAL}]}"


	cd ${ORIGEM}

	FILTROSATELITE="S*"
	TOTALCENAS="`find ${ORIGEM}/${FILTROPERIODO}/GVAR/LINUX  -name ${FILTROSATELITE}  -print | wc -l`"
	TOTALGERAL=${TOTALCENAS}

	
	FILTROSATELITE="GOES*"
	TOTALCENAS="`find ${ORIGEM}/${FILTROPERIODO}/CP*  -name ${FILTROSATELITE}  -print | wc -l`"

	TOTALGERAL=$(( ${TOTALGERAL} + ${TOTALCENAS} ))
	TOTALGERAL=$(( ${TOTALCENAS} * ${FATORDISTRIBUICAO} ))

	echo "${NOMESATELITE} : ${TOTALCENAS}  -  ${FATORDISTRIBUICAO}  -  ${TOTALGERAL}"
	
	echo "${CAMPOANO};${FONTEDADOS};${NOMESATELITE};${TOTALCENAS}"  >>  ${ARQUIVOSAIDA}
	
done
	

cd ${DIRATUAL}

